"""Build a single executor script from the three maintained Luau sources."""
import hashlib
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "dist"
MODULES = [("map_egg_search.luau", "createMapEggSearch"),
           ("egg_filter_panel.luau", "mountEggFilterPanel")]


def build():
    parts = ["-- Chilli Egg Finder: generated by build.py; edit the source modules.\n"]
    for filename, name in MODULES:
        source = (ROOT / filename).read_text(encoding="utf-8").strip()
        assert source.endswith("return " + name), f"Unexpected module export: {filename}"
        parts.append(f"local {name} = (function()\n{source}\nend)()\n")
    parts.append((ROOT / "hopper_runtime.luau").read_text(encoding="utf-8").rstrip() + "\n")
    OUT.mkdir(exist_ok=True)
    bundle = "".join(parts).encode("utf-8")
    (OUT / "chilli_hopper.luau").write_bytes(bundle)
    (OUT / "loader.luau").write_bytes((ROOT / "loader.luau").read_bytes())
    sha = hashlib.sha256(bundle).hexdigest()
    manifest = {"source_commit": os.getenv("GITHUB_SHA", "local"),
                "run": os.getenv("GITHUB_RUN_NUMBER", "local"),
                "sha256": sha, "bytes": len(bundle), "luau": "0.741"}
    (OUT / "version.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (OUT / "SHA256SUMS").write_text(f"{sha}  chilli_hopper.luau\n", encoding="utf-8")
    print(f"Built {len(bundle)} bytes; SHA256 {sha}")


if __name__ == "__main__":
    build()
